JobPortalMVC/Models/login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JobPortalMVC.Models
{
    public class login
    {
       // [Required(ErrorMessage ="Enter your Username")]
        public string username { get; set; }
       // [Required(ErrorMessage = "Enter your Password")]
        public string password { get; set; }

        public string msg { get; set; }
    }
}

JobPortalMVC/Controllers/AdminRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVC.Models;

namespace JobPortalMVC.Controllers
{
    public class AdminRegController : Controller
    {
        Job_Portal_WebsiteEntities dbobj = new Job_Portal_WebsiteEntities();
        // GET: AdminReg

        public ActionResult Page_Load()
        {
            return View();
        }

        public ActionResult Insert_Click(AdminInsert clsobj)
        {
            if (ModelState.IsValid)
            {
                var count = dbobj.sp_regCount().FirstOrDefault();
                int RegId = 0;
                int id = Convert.ToInt32(count);
                if (id == 0)
                {
                    RegId = 1;
                }
                else
                {
                    RegId = id + 1;
                }
                dbobj.sp_AdminReg(RegId, clsobj.Admin_Name, clsobj.Company_Name, clsobj.Company_Description);
                dbobj.sp_LoginInsert(RegId, clsobj.username, clsobj.cpassword, "Admin");
                clsobj.msg = "inserted successfully";

                return View("Page_Load", clsobj);
            }
            return View("Page_Load", clsobj);


        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

JobPortalMVC/Controllers/JobInsertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVC.Models;

namespace JobPortalMVC.Controllers
{
    public class JobInsertController : Controller
    {
        Job_Portal_WebsiteEntities dbobj = new Job_Portal_WebsiteEntities();
        // GET: JobInsert
        public ActionResult Page_Load()
        {
            return View();
        }

        public ActionResult Insert_Click(Job clsobj)
        {
            if (ModelState.IsValid)
            {
                int adminid = Convert.ToInt32(Session["uid"]);
                dbobj.sp_JobInsert(adminid, clsobj.Title, clsobj.Description, clsobj.Experiance, clsobj.Skills, clsobj.Location, clsobj.Job_Status, clsobj.Start_Date, clsobj.End_Date);
                clsobj.msg = "insert successfully";
                return View("Page_Load", clsobj);
            }
            return View("Page_Load", clsobj);
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

JobPortalMVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVC.Models;

namespace JobPortalMVC.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Job_Portal_WebsiteEntities dbobj = new Job_Portal_WebsiteEntities();

        public ActionResult Page_Load()

        {

            
            return View();

        }
        public ActionResult Login_click(login clsob)
        {
            if (ModelState.IsValid)
            {
                var count = dbobj.sp_LoginCount(clsob.username, clsob.password).FirstOrDefault()??0;
               // var count = dbobj.sp_LoginIdCount("Admin","000");
                //int ct = Convert.ToInt32(count);
                var type = dbobj.sp_LoginType(clsob.username, clsob.password).FirstOrDefault();
                var uid=dbobj.sp_AdminId(clsob.username, clsob.password).FirstOrDefault();
                Session["uid"] = uid;
                //string typ = type.ToString();

                if (count == 1)
                {
                    if (type == "Admin")
                    {
                        return RedirectToAction("AdminHome");

                    }
                    else if (type == "User")
                    {
                        return RedirectToAction("Jobview_Pageload","Search");
                       // return RedirectToAction("UserHome");

                    }

                }
                else
                {
                    clsob.msg = "Invalid";
                    return View("Page_Load", clsob);
                   

                }

            }
           

            return View("Page_Load", clsob);
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AdminHome()
        {
            return View();
        }
        public ActionResult UserHome( )
        {
           // ob.selectjob = dbobj.Job_Tab.ToList();
            return View(dbobj.Job_Tab.ToList());
        }
    }
}

JobPortalMVC/Controllers/UserRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalMVC.Models;

namespace JobPortalMVC.Controllers
{
    public class UserRegController : Controller
    {
        // GET: UserReg
        Job_Portal_WebsiteEntities dbobj = new Job_Portal_WebsiteEntities();

        public ActionResult Page_Load()
        {

            UserInsert us = new UserInsert();
            us.favQuali = getQualificationData();
            us.favSkill = getSkillData();
            return View(us);

        }
        public List<Quali> getQualificationData()
        {
            List<Quali> qul = new List<Quali>()
            {
                new Quali{value="SSLC",text="SSLC",IsChecked=true},
              new Quali{value="Plus Two",text="Plus Two",IsChecked=false},
              new Quali{value="BTECH",text="BTECH",IsChecked=false},
              new Quali{value="BCA",text="BCA",IsChecked=false},
              new Quali{value="MCA",text="MCA",IsChecked=false},
            };
            return qul;
        }
        public List<Skills> getSkillData()
        {
            List<Skills> sk = new List<Skills>()
            {
                new Skills{value="Python",text="Python",IsChecked=true},
              new Skills{value="Java",text="Java",IsChecked=false},
              new Skills{value="C#",text="C#",IsChecked=false},
              new Skills{value="MVC",text="MVC",IsChecked=false},
              new Skills{value=".Net",text=".NET",IsChecked=false},
            };
            return sk;
        }
        public ActionResult Insert_Click(UserInsert clsobj)
        {
            if (ModelState.IsValid)
            {
                var quid = string.Join(",", clsobj.selectedqual);
                clsobj.Qualification = quid;
                clsobj.favQuali = getQualificationData();

                var sid = string.Join(",", clsobj.selecetdskill);
                clsobj.Skills = sid;
                clsobj.favSkill = getSkillData();
                var count = dbobj.sp_regCount().FirstOrDefault();
                //var regid=dbobj.sp_LoginCount(clsobj.username, clsobj.password).FirstOrDefault();
                int RegId = 0;
                int id = Convert.ToInt32(count);

                if (id == 0)
                {
                    RegId = 1;
                }
                else
                {
                    RegId = id+ 1;
                }
                dbobj.sp_UserReg(RegId, clsobj.username, clsobj.User_Email, clsobj.User_Dob, clsobj.Ph, clsobj.ExperianceInyear, clsobj.Skills, clsobj.Qualification, "Active");
                dbobj.sp_LoginInsert(RegId, clsobj.username, clsobj.cpassword, "User");
                clsobj.msg = "successfully inserted";
                return View("Page_Load", clsobj);


            }
            else
            {
                clsobj.favQuali = getQualificationData();
                clsobj.favSkill = getSkillData();
                return View("Page_Load", clsobj);
            }
            return View("Page_Load", clsobj);

        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult AdminHome()
        {
            return View();
        }
    }
}

JobPortalMVC/Views/Login/AdminHome.cshtml
@{
    ViewBag.Title = "AdminHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdminHome</h2>

<div>
    @Html.ActionLink("Add Job","Page_Load","JobInsert")
</div>

JobPortalMVC/Views/Login/Page_Load.cshtml
@model JobPortalMVC.Models.login
@{
    ViewBag.Title = "Page_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Page_Load</h2>
<div>
    @using (Html.BeginForm("Login_click", "Login", FormMethod.Post))
    {
        <div>
            <label>Username</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>
        <div>
            <label>Password</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.password)
            @Html.ValidationMessageFor(m => m.password)
        </div>

        <div>
            <input type="submit" value="Login" />
            @Html.DisplayFor(m => m.msg)
        </div>
        <div>
           @Html.ActionLink("User Registration","Page_Load","UserReg")
            @Html.ActionLink("Admin Registration","Page_Load","AdminReg")
            
        </div>


    }
</div>

JobPortalMVC/Views/Login/UserHome.cshtml
@model JobPortalMVC.Models.Jobsearch
@*@model IEnumerable<JobPortalMVC.Job_Tab>*@
@{
    ViewBag.Title = "UserHome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UserHome</h2>

<div>

    @using (Html.BeginForm("searchJob_click", "Search", FormMethod.Post))
    {
        <table style="width:100%; border: 1px solid lightgray; background-color:lightgray;">
            <tr>
                <td style="width:25%; padding-right:10px;">
                    @Html.TextBoxFor(m => m.insertse.Job_skills, new { @style = "width:100%;", placeholder = "Skills" })

                </td>
                <td style="width:25%; padding-right:10px;">
                    @Html.TextBoxFor(m => m.insertse.Job_Experiance, new { @style = "width:100%", placeholder = "Experiance" })

                </td>
                <td style="width:25%; padding-right:10px;">
                    @Html.TextBoxFor(m => m.insertse.Location, new { @style = "width:100%", placeholder = "Location" })

                </td>
                <td style="width:25%; text-align:right;">
                    <input type="submit" value="Search" class="button" style="background-color:navy; color:white; padding:5px 10px;" />

                </td>
            </tr>

        </table>
    }

    <table>
        <tr>
            <th>@Html.DisplayNameFor(m => m.Title) </th>

            <th>@Html.DisplayNameFor(m => m.Description) </th>

            <th>@Html.DisplayNameFor(m => m.Experiance) </th>

            <th>@Html.DisplayNameFor(m => m.Skills) </th>
            <th>@Html.DisplayNameFor(m => m.Location) </th>
            <th>@Html.DisplayNameFor(m => m.Job_Status) </th>
            <th>@Html.DisplayNameFor(m => m.Start_Date) </th>
            <th>@Html.DisplayNameFor(m => m.End_Date) </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Experiance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Skills)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Job_Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.End_Date)
                </td>

            </tr>

        }
    </table>
</div>